name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check --all-targets --all-features --locked
      - name: Test
        run: RUST_TEST_THREADS=1 cargo test --all-targets --all-features --locked
      - name: Clippy
        run: cargo clippy --all-targets --all-features --locked -- -D warnings
